### ISSUE TITLE
Can not build: multiple definition of `energymon_path'

### ISSUE THREAD

**Issue by cyring** [amd/esmi_ib_library#2]
Hello,

Trying to build with the followings:
```
cd ~/tmp
git clone https://github.com/amd/esmi_ib_library.git
cd esmi_ib_library/
mkdir build
cd build

cmake ~/tmp/esmi_ib_library/
-- Build files have been written to: ~/tmp/esmi_ib_library/build

make
[ 50%] Linking C shared library libe_smi64.so
/usr/bin/ld: CMakeFiles/e_smi64.dir/src/e_smi_monitor.c.o:(.bss+0x0): multiple definition of `energymon_path'; CMakeFiles/e_smi64.dir/src/e_smi.c.o:(.bss+0x0): first defined here
/usr/bin/ld: CMakeFiles/e_smi64.dir/src/e_smi_monitor.c.o:(.bss+0x100): multiple definition of `hsmpmon_path'; CMakeFiles/e_smi64.dir/src/e_smi.c.o:(.bss+0x100): first defined here
collect2: error: ld returned 1 exit status
make[2]: *** [CMakeFiles/e_smi64.dir/build.make:136: libe_smi64.so.1.1] Error 1
```

Any clue ?

**Comment by nchatrad** [comment]
Hi @cyring 

I've tried building with the following versions and it builds fine on an x86_64 machine.

esmi_ib_library/build$ /usr/bin/cc --version
cc (Ubuntu 8.4.0-1ubuntu1~18.04) 8.4.0
...
esmi_ib_library/build$ make --version
GNU Make 4.1
Built for x86_64-pc-linux-gnu
...
esmi_ib_library/build$ cmake --version
cmake version 3.10.2
...

**Comment by cyring** [comment]
Indeed no issue to build with Ubuntu 18.04.5 LTS and 20.04 LTS

So I have to solve the packages issue with Arch, especially around that C and C++ rows marked as skipped.
```
cmake ~/tmp/esmi_ib_library/
7 commit/s found since previous release
Package version: 1.1.0.7.local-build-0-c769143
SOVERSION: 1.1
-- The C compiler identification is GNU 10.2.0
-- The CXX compiler identification is GNU 10.2.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Could NOT find Doxygen (missing: DOXYGEN_EXECUTABLE) 
Doxygen is not found. Will not generate documents.
-- Configuring done
-- Generating done
-- Build files have been written to: ~/tmp/esmi_ib_library/build
```

Sorry for the noise.
